# Generated by Django 3.0.6 on 2020-06-01 20:07

from django.db import migrations, models
import django.db.models.deletion
import drive.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course', models.IntegerField()),
                ('specialty', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('path', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(default='static/default_img.jpg', upload_to=drive.models.content_file_name)),
                ('file', models.FileField(blank=True, null=True, upload_to=drive.models.content_file_name)),
                ('course_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.Courses')),
            ],
        ),
    ]
