# Generated by Django 3.0.6 on 2020-05-30 10:02

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('data', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/shared_files'), upload_to='')),
            ],
        ),
    ]
