# Generated by Django 3.0.6 on 2020-06-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='rating_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='rating_votes',
            field=models.IntegerField(default=0),
        ),
    ]
