# Generated by Django 3.0.6 on 2020-05-31 20:08

from django.db import migrations, models
import drive.models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_auto_20200531_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='course',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='speciality',
            field=models.TextField(default='cs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='subject',
            field=models.TextField(default='Math1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to=drive.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=drive.models.content_file_name),
        ),
    ]
