# Generated by Django 3.0.6 on 2020-05-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0004_auto_20200531_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='course',
            field=models.IntegerField(null=True),
        ),
    ]
