# Generated by Django 3.0.6 on 2020-06-04 09:35

from django.db import migrations, models
import drive.models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0005_comments_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='static/default_img.png', upload_to=drive.models.content_file_name),
        ),
    ]
